// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHoqP4WkSOUOvLVBpBJXOuTwqDpCG7eE',
    appId: '1:958010718591:web:0c695bf2c755829007024a',
    messagingSenderId: '958010718591',
    projectId: 'servicer-311e5',
    authDomain: 'servicer-311e5.firebaseapp.com',
    storageBucket: 'servicer-311e5.firebasestorage.app',
    measurementId: 'G-NY7H8W5BPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsrc54nQ2qye_2qaoNNUZK_0acwsqo2Mk',
    appId: '1:958010718591:android:b7874fc0cf09334607024a',
    messagingSenderId: '958010718591',
    projectId: 'servicer-311e5',
    storageBucket: 'servicer-311e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD75cYqhWmMGdlY00ZOobYAJQJa6B2Uxso',
    appId: '1:958010718591:ios:9d265d5523b0935b07024a',
    messagingSenderId: '958010718591',
    projectId: 'servicer-311e5',
    storageBucket: 'servicer-311e5.firebasestorage.app',
    iosBundleId: 'com.example.servicer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD75cYqhWmMGdlY00ZOobYAJQJa6B2Uxso',
    appId: '1:958010718591:ios:9d265d5523b0935b07024a',
    messagingSenderId: '958010718591',
    projectId: 'servicer-311e5',
    storageBucket: 'servicer-311e5.firebasestorage.app',
    iosBundleId: 'com.example.servicer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHoqP4WkSOUOvLVBpBJXOuTwqDpCG7eE',
    appId: '1:958010718591:web:78b2b1614d1108f907024a',
    messagingSenderId: '958010718591',
    projectId: 'servicer-311e5',
    authDomain: 'servicer-311e5.firebaseapp.com',
    storageBucket: 'servicer-311e5.firebasestorage.app',
    measurementId: 'G-5S4ZKXZ2B9',
  );
}
